name: weather_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_bloc: ^8.1.5
  bloc_concurrency: ^0.2.5
  logger: ^2.2.0
  auto_route: ^8.0.2
  dio: ^5.4.2+1
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.2
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  freezed: ^2.4.7

flutter:
#  generate: true
  uses-material-design: true
  assets:
    - assets/
